### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'fetch_archive'

### ISSUE THREAD

**Issue by t25kim** [chaoss/grimoirelab-perceval#327]
$ perceval git https://github.com/chaoss/grimoirelab-perceval.git
[2018-02-19 19:58:16,107] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/extra_storage/staging/venvs/grimoirelab/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.10', 'perceval')
  File "/extra_storage/staging/venvs/grimoirelab/lib/python3.5/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/extra_storage/staging/venvs/grimoirelab/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/extra_storage/staging/venvs/grimoirelab/lib/python3.5/site-packages/perceval-0.9.10-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/extra_storage/staging/venvs/grimoirelab/lib/python3.5/site-packages/perceval-0.9.10-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/extra_storage/staging/venvs/grimoirelab/lib/python3.5/site-packages/perceval-0.9.10-py3.5.egg/perceval/backend.py", line 354, in run
    if self.parsed_args.fetch_archive:
AttributeError: 'Namespace' object has no attribute 'fetch_archive'

**Comment by sduenas** [comment]
Thanks for the bug report. #328 PR fixes this problem.

**Comment by sduenas** [comment]
Fixed

**Comment by sulunemre** [comment]
Hi, the issue is still in the docker image. I think you should rebuild and push
https://hub.docker.com/r/grimoirelab/perceval/

**Comment by jgbarah** [comment]
Instead of using that Image, please have a look at the "community" (ready to use) images. Yo can find info about them in [SirMorderd in a container](https://chaoss.github.io/grimoirelab-tutorial/sirmordred/container.html), and in the [GitHub directory with info & data about the Docker images](https://github.com/chaoss/grimoirelab/tree/master/docker). Those are following GrimoireLab releases, so should have that fixed. Please, open a ticker in chaoss/grimoirelab if they still show this bug (or any other).
