### ISSUE TITLE
Installing from source code doesn't work

### ISSUE THREAD

**Issue by sulunemre** [chaoss/grimoirelab-perceval#696]
Hey, I am trying to install perceval from source code. After cloning the repo, I run `pip install -r requirements.txt` command but it fails with an error: `ModuleNotFoundError: No module named 'setuptools'`.

Even after I install setuptools with `apt-get install python3-setuptools`, I get the same error message. Here is the full output of pip install command:

```
Cloning into 'grimoirelab-perceval'...
Collecting python-dateutil>=2.6.0
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting requests>=2.7.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting beautifulsoup4>=4.3.2
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting feedparser>=5.1.3
  Downloading feedparser-6.0.1-py2.py3-none-any.whl (80 kB)
Collecting dulwich>=0.20.0
  Downloading dulwich-0.20.6-cp37-cp37m-manylinux2010_x86_64.whl (503 kB)
Collecting urllib3>=1.22
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Obtaining grimoirelab-toolkit from git+https://github.com/chaoss/grimoirelab-toolkit/#egg=grimoirelab-toolkit (from -r requirements.txt (line 7))
  Cloning https://github.com/chaoss/grimoirelab-toolkit/ to ./src/grimoirelab-toolkit
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py): started
  Building wheel for sgmllib3k (setup.py): finished with status 'done'
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6064 sha256=fd07dbddb00e3bbd5635221e594803f8f9e38f58fcebc5963767b71980b9a054
  Stored in directory: /root/.cache/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built sgmllib3k
Installing collected packages: six, python-dateutil, chardet, idna, certifi, urllib3, requests, soupsieve, beautifulsoup4, sgmllib3k, feedparser, dulwich, grimoirelab-toolkit
  Running setup.py develop for grimoirelab-toolkit
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/src/app/grimoirelab-perceval/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/usr/src/app/grimoirelab-perceval/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /usr/src/app/grimoirelab-perceval/src/grimoirelab-toolkit/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/src/app/grimoirelab-perceval/src/grimoirelab-toolkit/setup.py'"'"'; __file__='"'"'/usr/src/app/grimoirelab-perceval/src/grimoirelab-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Python version: 3.7.8

**Comment by sduenas** [comment]
Yeah, this is a problem we are facing since the latest updates on `setuptools`. I thought it was fixed but apparently is not. You can have more info here: https://github.com/pypa/setuptools/issues/2353. There are some workarounds on that issue to fix the problem. Not sure which ones really work because I could fix it setting an environment variable but other people tried the same and it didn't work for them.

In any case, I'll try to check this later. Let's keep this open until we find a solution for this.

**Comment by sulunemre** [comment]
Thank you for pointing the issue. It works after downgrading setuptools and pip. Working example:

```
git clone https://github.com/chaoss/grimoirelab-perceval.git && \cd grimoirelab-perceval && \
pip install --upgrade pip==18.1 setuptools==49.6.0 && \
pip install -r requirements.txt && \
pip install .
```

**Comment by s0mnaths** [comment]
> Thank you for pointing the issue. It works after downgrading setuptools and pip. Working example:
> 
> ```
> git clone https://github.com/chaoss/grimoirelab-perceval.git && \
> cd grimoirelab-perceval && \
> pip install --upgrade pip==18.1 setuptools==49.6.0 && \
> pip install -r requirements.txt && \
> pip install .
> ```

It still shows the same error for me, after running the above lines.

**Comment by vchrombie** [comment]
Hi @s0mnaths 

> It still shows the same error for me, after running the above lines. Can you suggest something?

If you don't have any source code requirement, can you try installing the pip package?
```
$ pip3 install perceval
```

**Comment by s0mnaths** [comment]
> Hi @s0mnaths
> 
> > It still shows the same error for me, after running the above lines. Can you suggest something?
> 
> If you don't have any source code requirement, can you try installing the pip package?
> 
> ```
> $ pip3 install perceval
> ```

Thanks! That worked for me.

**Comment by sulunemre** [comment]
The releases on pip were old when I had opened this issue, but it looks like they are updated now, and installing from source is no more needed for me.  Thanks!

**Comment by sduenas** [comment]
Yes, we have been updating the packages on pypi. Sorry because I forgot to notify it.
